import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    drivers: 'Drivers',
    vehicles: 'Vehicles',
    trips: 'Trips',
    reports: 'Reports',
    settings: 'Settings',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    search: 'Search',
    filter: 'Filter',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Login
    emailAddress: 'Email Address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    signIn: 'Sign In',
    demoCredentials: 'Demo Credentials',
    driver: 'Driver',
    owner: 'Owner',
    professionalLimousineService: 'Professional limousine service management',
    
    // Settings
    profileInformation: 'Profile Information',
    languageRegional: 'Language & Regional',
    fullName: 'Full Name',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    language: 'Language',
    timezone: 'Timezone',
    applicationInformation: 'Application Information',
    appVersion: 'App Version',
    lastUpdated: 'Last Updated',
    build: 'Build',
    environment: 'Environment',
    manageAccountSettings: 'Manage your account settings and preferences',
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    emailInvalid: 'Email is invalid',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordsNotMatch: 'Passwords do not match',
    currentPasswordRequired: 'Current password is required to change password',
    settingsSaved: 'Settings saved successfully!',
    failedToSave: 'Failed to save settings. Please try again.',
    failedToLoad: 'Failed to load settings',
    languagePreview: 'Language Preview',
    currentLanguage: 'Current language',
    languageChangesNote: 'Language changes will be applied after saving and refreshing the page.',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    
    // Trip Form
    pickupLocation: 'Pickup Location',
    startTime: 'Start Time',
    endTime: 'End Time',
    numberOfPassengers: 'Number of Passengers',
    clientName: 'Client Name',
    additionalNotes: 'Additional Notes',
    selectDriver: 'Select a driver',
    selectVehicle: 'Select a vehicle',
    createTrip: 'Create Trip',
    driverRequired: 'Driver is required',
    vehicleRequired: 'Vehicle is required',
    pickupRequired: 'Pickup location is required',
    destinationRequired: 'Destination is required',
    dateRequired: 'Date is required',
    startTimeRequired: 'Start time is required',
    endTimeRequired: 'End time is required',
    passengersRequired: 'Number of passengers is required',
    clientRequired: 'Client name is required',
    revenueRequired: 'Revenue is required',
    tripCreatedSuccessfully: 'Trip created successfully!',
    failedToCreateTrip: 'Failed to create trip. Please try again.',
    creatingTrip: 'Creating Trip...',
    endTimeAfterStart: 'End time must be after start time',
    cannotExceedCapacity: 'Cannot exceed vehicle capacity',
    addVehicle: 'Add Vehicle',
    manageVehicleFleet: 'Manage your vehicle fleet',
    active: 'Active',
    maintenance: 'Maintenance',
    outOfService: 'Out of Service',
    currentLocation: 'Current Location',
    fuelLevel: 'Fuel Level',
    mileage: 'Mileage',
    lastService: 'Last Service',
    nextService: 'Next Service',
    capacity: 'Capacity',
    type: 'Type',
    overviewOfLimousineService: 'Overview of your limousine service',
    viewAll: 'View All',
    quickActions: 'Quick Actions',
    manageDrivers: 'Manage Drivers',
    vehicleStatus: 'Vehicle Status',
    hoursAgo: 'hours ago',
    minutesAgo: 'minutes ago',
    hourAgo: 'hour ago',
    completedStatus: 'completed',
    activeStatus: 'active',
    assignedStatus: 'assigned',
    manageDriverTeam: 'Manage your driver team',
    addDriver: 'Add Driver',
    totalDrivers: 'Total Drivers',
    offline: 'Offline',
    contact: 'Contact',
    performance: 'Performance',
    location: 'Location',
    lastActive: 'Last active',
    rating: 'Rating',
    offlineStatus: 'offline',
    totalVehicles: 'Total Vehicles',
    totalCapacity: 'Total Capacity',
    passengers: 'passengers',
    fuel: 'Fuel',
    mi: 'mi',
    viewDetails: 'View Details',
    trackLocation: 'Track Location',
    
    // Driver Dashboard
    myTrips: 'My Trips',
    earnings: 'Earnings',
    profile: 'Profile',
    welcomeBack: 'Welcome back',
    noTripsScheduled: 'No trips scheduled',
    noTripsMessage: "You don't have any trips assigned at the moment.",
    startTrip: 'Start Trip',
    completeTrip: 'Complete Trip',
    tripCompleted: 'Trip Completed',
    navigate: 'Navigate',
    thisWeek: 'This Week',
    totalEarnings: 'Total Earnings',
    tripStatistics: 'Trip Statistics',
    successRate: 'Success Rate',
    professionalDriver: 'Professional Driver',
    notifications: 'Notifications',
    privacy: 'Privacy',
    signOut: 'Sign Out',
    assigned: 'Assigned',
    onTheWay: 'On the Way',
    cancelled: 'Cancelled',
    phone: 'Phone',
    notes: 'Notes',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    pickup: 'Pickup',
    destination: 'Destination',
    vehicle: 'Vehicle'
  },
  
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    drivers: 'Chauffeurs',
    vehicles: 'Véhicules',
    trips: 'Trajets',
    reports: 'Rapports',
    settings: 'Paramètres',
    
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    add: 'Ajouter',
    create: 'Créer',
    update: 'Mettre à jour',
    search: 'Rechercher',
    filter: 'Filtrer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    
    // Login
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    enterEmail: 'Entrez votre e-mail',
    enterPassword: 'Entrez votre mot de passe',
    signIn: 'Se connecter',
    demoCredentials: 'Identifiants de démonstration',
    driver: 'Chauffeur',
    owner: 'Propriétaire',
    professionalLimousineService: 'Gestion professionnelle de service de limousine',
    
    // Settings
    profileInformation: 'Informations du profil',
    languageRegional: 'Langue et région',
    fullName: 'Nom complet',
    changePassword: 'Changer le mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le nouveau mot de passe',
    language: 'Langue',
    timezone: 'Fuseau horaire',
    applicationInformation: 'Informations sur l\'application',
    appVersion: 'Version de l\'app',
    lastUpdated: 'Dernière mise à jour',
    build: 'Build',
    environment: 'Environnement',
    manageAccountSettings: 'Gérez vos paramètres de compte et préférences',
    nameRequired: 'Le nom est requis',
    emailRequired: 'L\'email est requis',
    emailInvalid: 'L\'email n\'est pas valide',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    passwordsNotMatch: 'Les mots de passe ne correspondent pas',
    currentPasswordRequired: 'Le mot de passe actuel est requis pour changer le mot de passe',
    settingsSaved: 'Paramètres enregistrés avec succès !',
    failedToSave: 'Échec de l\'enregistrement des paramètres. Veuillez réessayer.',
    failedToLoad: 'Échec du chargement des paramètres',
    languagePreview: 'Aperçu de la langue',
    currentLanguage: 'Langue actuelle',
    languageChangesNote: 'Les changements de langue seront appliqués après l\'enregistrement et le rafraîchissement de la page.',
    saving: 'Enregistrement...',
    saveChanges: 'Enregistrer les modifications',
    
    // Trip Form
    pickupLocation: 'Lieu de prise en charge',
    startTime: 'Heure de début',
    endTime: 'Heure de fin',
    numberOfPassengers: 'Nombre de passagers',
    clientName: 'Nom du client',
    additionalNotes: 'Notes supplémentaires',
    selectDriver: 'Sélectionner un chauffeur',
    selectVehicle: 'Sélectionner un véhicule',
    createTrip: 'Créer le trajet',
    driverRequired: 'Le chauffeur est requis',
    vehicleRequired: 'Le véhicule est requis',
    pickupRequired: 'Le lieu de prise en charge est requis',
    destinationRequired: 'La destination est requise',
    dateRequired: 'La date est requise',
    startTimeRequired: 'L\'heure de début est requise',
    endTimeRequired: 'L\'heure de fin est requise',
    passengersRequired: 'Le nombre de passagers est requis',
    clientRequired: 'Le nom du client est requis',
    revenueRequired: 'Les revenus sont requis',
    tripCreatedSuccessfully: 'Trajet créé avec succès !',
    failedToCreateTrip: 'Échec de la création du trajet. Veuillez réessayer.',
    creatingTrip: 'Création du trajet...',
    endTimeAfterStart: 'L\'heure de fin doit être après l\'heure de début',
    cannotExceedCapacity: 'Ne peut pas dépasser la capacité du véhicule',
    addVehicle: 'Ajouter un véhicule',
    manageVehicleFleet: 'Gérez votre flotte de véhicules',
    active: 'Actif',
    maintenance: 'Maintenance',
    outOfService: 'Hors service',
    currentLocation: 'Localisation actuelle',
    fuelLevel: 'Niveau de carburant',
    mileage: 'Kilométrage',
    lastService: 'Dernier service',
    nextService: 'Prochain service',
    capacity: 'Capacité',
    type: 'Type',
    overviewOfLimousineService: 'Aperçu de votre service de limousine',
    viewAll: 'Voir tout',
    quickActions: 'Actions rapides',
    manageDrivers: 'Gérer les chauffeurs',
    vehicleStatus: 'Statut des véhicules',
    hoursAgo: 'heures',
    minutesAgo: 'minutes',
    hourAgo: 'heure',
    completedStatus: 'terminé',
    activeStatus: 'actif',
    assignedStatus: 'assigné',
    manageDriverTeam: 'Gérez votre équipe de chauffeurs',
    addDriver: 'Ajouter un chauffeur',
    totalDrivers: 'Total des chauffeurs',
    offline: 'Hors ligne',
    contact: 'Contact',
    performance: 'Performance',
    location: 'Localisation',
    lastActive: 'Dernière activité',
    rating: 'Note',
    offlineStatus: 'hors ligne',
    totalVehicles: 'Total des véhicules',
    totalCapacity: 'Capacité totale',
    passengers: 'passagers',
    fuel: 'Carburant',
    mi: 'km',
    viewDetails: 'Voir les détails',
    trackLocation: 'Suivre la localisation',
    
    // Driver Dashboard
    myTrips: 'Mes trajets',
    earnings: 'Gains',
    profile: 'Profil',
    welcomeBack: 'Bon retour',
    noTripsScheduled: 'Aucun trajet programmé',
    noTripsMessage: "Vous n'avez aucun trajet assigné pour le moment.",
    startTrip: 'Commencer le trajet',
    completeTrip: 'Terminer le trajet',
    tripCompleted: 'Trajet terminé',
    navigate: 'Naviguer',
    thisWeek: 'Cette semaine',
    totalEarnings: 'Gains totaux',
    tripStatistics: 'Statistiques des trajets',
    successRate: 'Taux de réussite',
    professionalDriver: 'Chauffeur professionnel',
    notifications: 'Notifications',
    privacy: 'Confidentialité',
    signOut: 'Se déconnecter',
    assigned: 'Assigné',
    onTheWay: 'En route',
    cancelled: 'Annulé',
    phone: 'Téléphone',
    notes: 'Notes',
    status: 'Statut',
    date: 'Date',
    time: 'Heure',
    pickup: 'Prise en charge',
    destination: 'Destination',
    vehicle: 'Véhicule'
  },
  
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    drivers: 'السائقين',
    vehicles: 'المركبات',
    trips: 'الرحلات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    create: 'إنشاء',
    update: 'تحديث',
    search: 'بحث',
    filter: 'تصفية',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    
    // Login
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPassword: 'أدخل كلمة المرور',
    signIn: 'تسجيل الدخول',
    demoCredentials: 'بيانات الاعتماد التجريبية',
    driver: 'السائق',
    owner: 'المالك',
    professionalLimousineService: 'إدارة خدمة الليموزين المهنية',
    
    // Settings
    profileInformation: 'معلومات الملف الشخصي',
    languageRegional: 'اللغة والمنطقة',
    fullName: 'الاسم الكامل',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    language: 'اللغة',
    timezone: 'المنطقة الزمنية',
    applicationInformation: 'معلومات التطبيق',
    appVersion: 'إصدار التطبيق',
    lastUpdated: 'آخر تحديث',
    build: 'البناء',
    environment: 'البيئة',
    manageAccountSettings: 'إدارة إعدادات حسابك وتفضيلاتك',
    nameRequired: 'الاسم مطلوب',
    emailRequired: 'البريد الإلكتروني مطلوب',
    emailInvalid: 'البريد الإلكتروني غير صحيح',
    passwordMinLength: 'كلمة المرور يجب أن تحتوي على 6 أحرف على الأقل',
    passwordsNotMatch: 'كلمات المرور غير متطابقة',
    currentPasswordRequired: 'كلمة المرور الحالية مطلوبة لتغيير كلمة المرور',
    settingsSaved: 'تم حفظ الإعدادات بنجاح!',
    failedToSave: 'فشل في حفظ الإعدادات. يرجى المحاولة مرة أخرى.',
    failedToLoad: 'فشل في تحميل الإعدادات',
    languagePreview: 'معاينة اللغة',
    currentLanguage: 'اللغة الحالية',
    languageChangesNote: 'سيتم تطبيق تغييرات اللغة بعد الحفظ وتحديث الصفحة.',
    saving: 'جاري الحفظ...',
    saveChanges: 'حفظ التغييرات',
    
    // Trip Form
    pickupLocation: 'موقع الاستلام',
    startTime: 'وقت البداية',
    endTime: 'وقت النهاية',
    numberOfPassengers: 'عدد الركاب',
    clientName: 'اسم العميل',
    additionalNotes: 'ملاحظات إضافية',
    selectDriver: 'اختر سائق',
    selectVehicle: 'اختر مركبة',
    createTrip: 'إنشاء الرحلة',
    driverRequired: 'السائق مطلوب',
    vehicleRequired: 'المركبة مطلوبة',
    pickupRequired: 'موقع الاستلام مطلوب',
    destinationRequired: 'الوجهة مطلوبة',
    dateRequired: 'التاريخ مطلوب',
    startTimeRequired: 'وقت البداية مطلوب',
    endTimeRequired: 'وقت النهاية مطلوب',
    passengersRequired: 'عدد الركاب مطلوب',
    clientRequired: 'اسم العميل مطلوب',
    revenueRequired: 'الإيرادات مطلوبة',
    tripCreatedSuccessfully: 'تم إنشاء الرحلة بنجاح!',
    failedToCreateTrip: 'فشل في إنشاء الرحلة. يرجى المحاولة مرة أخرى.',
    creatingTrip: 'جاري إنشاء الرحلة...',
    endTimeAfterStart: 'وقت النهاية يجب أن يكون بعد وقت البداية',
    cannotExceedCapacity: 'لا يمكن تجاوز سعة المركبة',
    addVehicle: 'إضافة مركبة',
    manageVehicleFleet: 'إدارة أسطول المركبات',
    active: 'نشط',
    maintenance: 'صيانة',
    outOfService: 'خارج الخدمة',
    currentLocation: 'الموقع الحالي',
    fuelLevel: 'مستوى الوقود',
    mileage: 'المسافة المقطوعة',
    lastService: 'آخر خدمة',
    nextService: 'الخدمة التالية',
    capacity: 'السعة',
    type: 'النوع',
    overviewOfLimousineService: 'نظرة عامة على خدمة الليموزين',
    viewAll: 'عرض الكل',
    quickActions: 'إجراءات سريعة',
    manageDrivers: 'إدارة السائقين',
    vehicleStatus: 'حالة المركبات',
    hoursAgo: 'ساعات',
    minutesAgo: 'دقائق',
    hourAgo: 'ساعة',
    completedStatus: 'مكتمل',
    activeStatus: 'نشط',
    assignedStatus: 'مخصص',
    manageDriverTeam: 'إدارة فريق السائقين',
    addDriver: 'إضافة سائق',
    totalDrivers: 'إجمالي السائقين',
    offline: 'غير متصل',
    contact: 'التواصل',
    performance: 'الأداء',
    location: 'الموقع',
    lastActive: 'آخر نشاط',
    rating: 'التقييم',
    offlineStatus: 'غير متصل',
    totalVehicles: 'إجمالي المركبات',
    totalCapacity: 'السعة الإجمالية',
    passengers: 'ركاب',
    fuel: 'الوقود',
    mi: 'كم',
    viewDetails: 'عرض التفاصيل',
    trackLocation: 'تتبع الموقع',
    
    // Driver Dashboard
    myTrips: 'رحلاتي',
    earnings: 'الأرباح',
    profile: 'الملف الشخصي',
    welcomeBack: 'مرحباً بعودتك',
    noTripsScheduled: 'لا توجد رحلات مجدولة',
    noTripsMessage: 'ليس لديك أي رحلات مخصصة في الوقت الحالي.',
    startTrip: 'بدء الرحلة',
    completeTrip: 'إكمال الرحلة',
    tripCompleted: 'تم إكمال الرحلة',
    navigate: 'التنقل',
    thisWeek: 'هذا الأسبوع',
    totalEarnings: 'إجمالي الأرباح',
    tripStatistics: 'إحصائيات الرحلات',
    successRate: 'معدل النجاح',
    professionalDriver: 'سائق محترف',
    notifications: 'الإشعارات',
    privacy: 'الخصوصية',
    signOut: 'تسجيل الخروج',
    assigned: 'مخصص',
    onTheWay: 'في الطريق',
    cancelled: 'ملغي',
    phone: 'الهاتف',
    notes: 'الملاحظات',
    status: 'الحالة',
    date: 'التاريخ',
    time: 'الوقت',
    pickup: 'الاستلام',
    destination: 'الوجهة',
    vehicle: 'المركبة'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    // Load language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('limostar-language') || 'en'
    setLanguage(savedLanguage)
    setIsLoading(false)
  }, [])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('limostar-language', newLanguage)
  }

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key
  }

  const value = {
    language,
    changeLanguage,
    t,
    isLoading
  }

  if (isLoading) {
    return <div>Loading...</div>
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}
