import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    plannings: 'Schedules',
    reports: 'Reports',
    facturations: 'Invoicing',
    notesCredit: 'Credit Notes',
    devis: 'Quotes',
    proforma: 'Proforma',
    drivers: 'Drivers',
    clients: 'Clients',
    profils: 'Profiles',
    compagnie: 'Company',
    vehicles: 'Vehicles',
    trips: 'Trips',
    settings: 'Settings',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    create: 'Create',
    update: 'Update',
    search: 'Search',
    filter: 'Filter',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Dashboard
    dashboardTitle: 'Dashboard',
    quickAccess: 'Quick Access',
    tripStatistics: 'Trip Statistics',
    totalToday: 'Total Today',
    tripsToDoToday: 'Trips to do today',
    tripsCompleted: 'Trips completed',
    todaysTrips: 'Today\'s trips',
    total: 'Total',
    time: 'Time',
    driver: 'Driver',
    departure: 'Departure',
    destination: 'Destination',
    passengers: 'Passengers',
    client: 'Client',
    payment: 'Payment',
    noTripsToday: 'No trips scheduled for today',
    revenue: 'Revenue',
    revenueChart: 'Revenue Chart',
    refresh: 'Refresh',
    maximize: 'Maximize',
    chartCombinations: 'Chart Combinations',
    trips: 'Trips',
    revenueAmount: 'Revenue',
    unpaidInvoices: 'Unpaid Invoices',
    averageTripPrice: 'Average Trip Price',
    months: 'Months',
    
    // Plannings
    planningsTitle: 'Plannings',
    newTrip: 'New Trip',
    addPlanning: 'Add Planning',
    day: 'Day',
    previous: 'Previous',
    next: 'Next',
    noTripsFound: 'No trips found',
    createTrip: 'Create Trip',
    tripCreatedSuccessfully: 'Trip created successfully!',
    failedToCreateTrip: 'Failed to create trip. Please try again.',
    creatingTrip: 'Creating Trip...',
    driverRequired: 'Driver is required',
    vehicleRequired: 'Vehicle is required',
    pickupRequired: 'Pickup location is required',
    destinationRequired: 'Destination is required',
    dateRequired: 'Date is required',
    startTimeRequired: 'Start time is required',
    endTimeRequired: 'End time is required',
    passengersRequired: 'Number of passengers is required',
    clientRequired: 'Client name is required',
    revenueRequired: 'Revenue is required',
    endTimeAfterStart: 'End time must be after start time',
    cannotExceedCapacity: 'Cannot exceed vehicle capacity',
    selectDriver: 'Select a driver',
    selectVehicle: 'Select a vehicle',
    mail: 'Mail',
    weekOf: 'Week of',
    
    // Reports
    reportsTitle: 'Reports',
    period: 'Period',
    show: 'Show',
    totalTrips: 'Total Trips',
    totalRevenue: 'Total Revenue',
    totalDistance: 'Total Distance',
    totalDuration: 'Total Duration',
    reportTitle: 'Trip Report',
    generatedOn: 'Generated on',
    all: 'All',
    allDrivers: 'All Drivers',
    allClients: 'All Clients',
    noReportsFound: 'No reports found',
    createReport: 'Create Report',
    reportCreatedSuccessfully: 'Report created successfully!',
    failedToCreateReport: 'Failed to create report. Please try again.',
    creatingReport: 'Creating Report...',
    distance: 'Distance',
    
    // Invoicing
    invoicingTitle: 'Invoicing',
    createInvoice: 'Create Invoice',
    invoiceNumber: 'Invoice Number',
    invoiceTable: 'Invoice Table',
    groupByClient: 'Group invoices by client',
    showMonth: 'Show month',
    display: 'Display',
    records: 'records',
    number: 'Number',
    dueDate: 'Due Date',
    paymentMethod: 'Payment Method',
    deposit: 'Deposit',
    remark: 'Remark',
    vatType: 'VAT Type',
    designations: 'Designations',
    description: 'Description',
    price: 'Price',
    trip: 'Trip',
    vat: 'VAT',
    totalExclVat: 'Total Excl. VAT',
    totalInclVat: 'Total Incl. VAT',
    clientType: 'Client Type',
    clientName: 'Client Name',
    clientAddress: 'Client Address',
    postalCode: 'Postal Code',
    city: 'City',
    clientVat: 'Client VAT',
    company: 'Company',
    addCompany: 'Add Company',
    invoiceCreatedSuccessfully: 'Invoice created successfully!',
    failedToCreateInvoice: 'Failed to create invoice. Please try again.',
    creatingInvoice: 'Creating Invoice...',
    
    // Credit Notes
    creditNotesTitle: 'Credit Notes',
    addCreditNote: 'Add Credit Note',
    creditNoteNumber: 'Credit Note Number',
    creditNotesTable: 'Credit Notes Table',
    totalPrice: 'Total Price',
    print: 'Print',
    creditNoteCreatedSuccessfully: 'Credit note created successfully!',
    failedToCreateCreditNote: 'Failed to create credit note. Please try again.',
    creatingCreditNote: 'Creating Credit Note...',
    
    // Quotes
    quotesTitle: 'Quotes',
    createQuote: 'Create Quote',
    quoteNumber: 'Quote Number',
    quotesTable: 'Quotes Table',
    quoteCreatedSuccessfully: 'Quote created successfully!',
    failedToCreateQuote: 'Failed to create quote. Please try again.',
    creatingQuote: 'Creating Quote...',
    
    // Proforma
    proformaTitle: 'Proforma',
    createProforma: 'Create Proforma',
    proformaNumber: 'Proforma Number',
    proformaTable: 'Proforma Table',
    proformaCreatedSuccessfully: 'Proforma created successfully!',
    failedToCreateProforma: 'Failed to create proforma. Please try again.',
    creatingProforma: 'Creating Proforma...',
    
    // Drivers
    driversTitle: 'Drivers',
    driversTable: 'Drivers Table',
    addDriver: 'Add Driver',
    modifyDriver: 'Modify Driver',
    driverStatus: 'Driver Status',
    inactive: 'Inactive',
    first: 'First',
    last: 'Last',
    driverNumber: 'Driver Number',
    driverName: 'Driver Name',
    driverEmail: 'Driver Email',
    driverPhone: 'Driver Phone',
    driverCreatedSuccessfully: 'Driver created successfully!',
    failedToCreateDriver: 'Failed to create driver. Please try again.',
    creatingDriver: 'Creating Driver...',
    driverUpdatedSuccessfully: 'Driver updated successfully!',
    failedToUpdateDriver: 'Failed to update driver. Please try again.',
    updatingDriver: 'Updating Driver...',
    driverDeletedSuccessfully: 'Driver deleted successfully!',
    failedToDeleteDriver: 'Failed to delete driver. Please try again.',
    deletingDriver: 'Deleting Driver...',
    
    // Clients
    clientsTitle: 'Clients',
    clientsTable: 'Clients Table',
    addClient: 'Add Client',
    modifyClient: 'Modify Client',
    clientNumber: 'Client Number',
    companyName: 'Company Name',
    fullAddress: 'Full Address',
    address: 'Address',
    country: 'Country',
    fax: 'Fax',
    email: 'Email',
    clientStatus: 'Client Status',
    actions: 'Actions',
    clientCreatedSuccessfully: 'Client created successfully!',
    failedToCreateClient: 'Failed to create client. Please try again.',
    creatingClient: 'Creating Client...',
    clientUpdatedSuccessfully: 'Client updated successfully!',
    failedToUpdateClient: 'Failed to update client. Please try again.',
    updatingClient: 'Updating Client...',
    clientDeletedSuccessfully: 'Client deleted successfully!',
    failedToDeleteClient: 'Failed to delete client. Please try again.',
    deletingClient: 'Deleting Client...',
    
    // Profiles
    profilesTitle: 'Profiles',
    profilesTable: 'Profiles Table',
    addProfile: 'Add Profile',
    modifyProfile: 'Modify Profile',
    profileName: 'Profile Name',
    username: 'Username',
    password: 'Password',
    class: 'Class',
    creationDate: 'Creation Date',
    modifyAccount: 'Modify Account',
    deleteAccount: 'Delete Account',
    profileClass: 'Profile Class',
    profileCreatedSuccessfully: 'Profile created successfully!',
    failedToCreateProfile: 'Failed to create profile. Please try again.',
    creatingProfile: 'Creating Profile...',
    profileUpdatedSuccessfully: 'Profile updated successfully!',
    failedToUpdateProfile: 'Failed to update profile. Please try again.',
    updatingProfile: 'Updating Profile...',
    profileDeletedSuccessfully: 'Profile deleted successfully!',
    failedToDeleteProfile: 'Failed to delete profile. Please try again.',
    deletingProfile: 'Deleting Profile...',
    
    // Company
    companyTitle: 'Company',
    companiesTitle: 'Companies',
    brandsTitle: 'Brands',
    addCompany: 'Add Company',
    modifyCompany: 'Modify Company',
    companyName: 'Company Name',
    website: 'Website',
    mobile: 'Mobile',
    companyCreatedSuccessfully: 'Company created successfully!',
    failedToCreateCompany: 'Failed to create company. Please try again.',
    creatingCompany: 'Creating Company...',
    companyUpdatedSuccessfully: 'Company updated successfully!',
    failedToUpdateCompany: 'Failed to update company. Please try again.',
    updatingCompany: 'Updating Company...',
    companyDeletedSuccessfully: 'Company deleted successfully!',
    failedToDeleteCompany: 'Failed to delete company. Please try again.',
    deletingCompany: 'Deleting Company...',
    addBrand: 'Add Brand',
    modifyBrand: 'Modify Brand',
    brandName: 'Brand Name',
    brandStatus: 'Brand Status',
    brandCreatedSuccessfully: 'Brand created successfully!',
    failedToCreateBrand: 'Failed to create brand. Please try again.',
    creatingBrand: 'Creating Brand...',
    brandUpdatedSuccessfully: 'Brand updated successfully!',
    failedToUpdateBrand: 'Failed to update brand. Please try again.',
    updatingBrand: 'Updating Brand...',
    brandDeletedSuccessfully: 'Brand deleted successfully!',
    failedToDeleteBrand: 'Failed to delete brand. Please try again.',
    deletingBrand: 'Deleting Brand...',
    
    // Login
    emailAddress: 'Email Address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    signIn: 'Sign In',
    demoCredentials: 'Demo Credentials',
    driver: 'Driver',
    owner: 'Owner',
    professionalLimousineService: 'Professional limousine service management',
    
    // Settings
    profileInformation: 'Profile Information',
    languageRegional: 'Language & Regional',
    fullName: 'Full Name',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    language: 'Language',
    timezone: 'Timezone',
    applicationInformation: 'Application Information',
    appVersion: 'App Version',
    lastUpdated: 'Last Updated',
    build: 'Build',
    environment: 'Environment',
    manageAccountSettings: 'Manage your account settings and preferences',
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    emailInvalid: 'Email is invalid',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordsNotMatch: 'Passwords do not match',
    currentPasswordRequired: 'Current password is required to change password',
    settingsSaved: 'Settings saved successfully!',
    failedToSave: 'Failed to save settings. Please try again.',
    failedToLoad: 'Failed to load settings',
    languagePreview: 'Language Preview',
    currentLanguage: 'Current language',
    languageChangesNote: 'Language changes will be applied after saving and refreshing the page.',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    
    // Trip Form
    pickupLocation: 'Pickup Location',
    startTime: 'Start Time',
    endTime: 'End Time',
    numberOfPassengers: 'Number of Passengers',
    clientName: 'Client Name',
    additionalNotes: 'Additional Notes',
    selectDriver: 'Select a driver',
    selectVehicle: 'Select a vehicle',
    createTrip: 'Create Trip',
    driverRequired: 'Driver is required',
    vehicleRequired: 'Vehicle is required',
    pickupRequired: 'Pickup location is required',
    destinationRequired: 'Destination is required',
    dateRequired: 'Date is required',
    startTimeRequired: 'Start time is required',
    endTimeRequired: 'End time is required',
    passengersRequired: 'Number of passengers is required',
    clientRequired: 'Client name is required',
    revenueRequired: 'Revenue is required',
    tripCreatedSuccessfully: 'Trip created successfully!',
    failedToCreateTrip: 'Failed to create trip. Please try again.',
    creatingTrip: 'Creating Trip...',
    endTimeAfterStart: 'End time must be after start time',
    cannotExceedCapacity: 'Cannot exceed vehicle capacity',
    addVehicle: 'Add Vehicle',
    manageVehicleFleet: 'Manage your vehicle fleet',
    active: 'Active',
    maintenance: 'Maintenance',
    outOfService: 'Out of Service',
    currentLocation: 'Current Location',
    fuelLevel: 'Fuel Level',
    mileage: 'Mileage',
    lastService: 'Last Service',
    nextService: 'Next Service',
    capacity: 'Capacity',
    type: 'Type',
    overviewOfLimousineService: 'Overview of your limousine service',
    viewAll: 'View All',
    quickActions: 'Quick Actions',
    manageDrivers: 'Manage Drivers',
    vehicleStatus: 'Vehicle Status',
    hoursAgo: 'hours ago',
    minutesAgo: 'minutes ago',
    hourAgo: 'hour ago',
    completedStatus: 'completed',
    activeStatus: 'active',
    assignedStatus: 'assigned',
    manageDriverTeam: 'Manage your driver team',
    addDriver: 'Add Driver',
    totalDrivers: 'Total Drivers',
    offline: 'Offline',
    contact: 'Contact',
    performance: 'Performance',
    location: 'Location',
    lastActive: 'Last active',
    rating: 'Rating',
    offlineStatus: 'offline',
    totalVehicles: 'Total Vehicles',
    totalCapacity: 'Total Capacity',
    passengers: 'passengers',
    fuel: 'Fuel',
    mi: 'mi',
    viewDetails: 'View Details',
    trackLocation: 'Track Location',
    manageAllServiceTrips: 'Manage all your service trips',
    assigned: 'Assigned',
    todaysRevenue: 'Today\'s Revenue',
    searchTrips: 'Search trips...',
    allStatus: 'All Status',
    route: 'Route',
    dateTime: 'Date & Time',
    trackTrip: 'Track Trip',
    noTripsFound: 'No trips found',
    tryAdjustingSearch: 'Try adjusting your search or filter criteria.',
    analyticsPerformanceInsights: 'Analytics and performance insights',
    export: 'Export',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    vsYesterday: 'vs yesterday',
    vsLastWeek: 'vs last week',
    vsLastMonth: 'vs last month',
    tripStatistics: 'Trip Statistics',
    completedTrips: 'Completed Trips',
    activeTrips: 'Active Trips',
    cancelledTrips: 'Cancelled Trips',
    topPerformingDrivers: 'Top Performing Drivers',
    vehicleUtilizationRevenue: 'Vehicle Utilization & Revenue',
    utilization: 'Utilization',
    excellent: 'Excellent',
    good: 'Good',
    needsAttention: 'Needs Attention',
    schedule: 'Schedule',
    calendar: 'Calendar',
    today: 'Today',
    tomorrow: 'Tomorrow',
    yesterday: 'Yesterday',
    week: 'Week',
    month: 'Month',
    noTripsToday: 'No trips scheduled for today',
    upcomingTrips: 'Upcoming Trips',
    tripDetails: 'Trip Details',
    startLocation: 'Start Location',
    endLocation: 'End Location',
    duration: 'Duration',
    estimatedArrival: 'Estimated Arrival',
    clientContact: 'Client Contact',
    specialInstructions: 'Special Instructions',
    viewOnMap: 'View on Map',
    markAsCompleted: 'Mark as Completed',
    markAsStarted: 'Mark as Started',
    cancelTrip: 'Cancel Trip',
    rescheduleTrip: 'Reschedule Trip',
    addToCalendar: 'Add to Calendar',
    calendarView: 'Calendar View',
    listView: 'List View',
    previousWeek: 'Previous Week',
    nextWeek: 'Next Week',
    previousMonth: 'Previous Month',
    nextMonth: 'Next Month',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    notifications: 'Notifications',
    notificationCenter: 'Notification Center',
    markAllAsRead: 'Mark All as Read',
    noNotifications: 'No notifications',
    newTripAssigned: 'New trip assigned',
    tripStatusChanged: 'Trip status changed',
    tripCompleted: 'Trip completed',
    tripCancelled: 'Trip cancelled',
    driverAssigned: 'Driver assigned',
    vehicleAssigned: 'Vehicle assigned',
    paymentReceived: 'Payment received',
    systemUpdate: 'System update',
    maintenanceReminder: 'Maintenance reminder',
    fuelLow: 'Fuel level low',
    justNow: 'Just now',
    daysAgo: 'days ago',
    read: 'Read',
    unread: 'Unread',
    clearAll: 'Clear All',
    notificationSettings: 'Notification Settings',
    enablePushNotifications: 'Enable Push Notifications',
    enableEmailNotifications: 'Enable Email Notifications',
    enableSMSNotifications: 'Enable SMS Notifications',
    tripNotifications: 'Trip Notifications',
    systemNotifications: 'System Notifications',
    maintenanceNotifications: 'Maintenance Notifications',
    notificationSound: 'Notification Sound',
    vibrationEnabled: 'Vibration Enabled',
    
    // Driver Dashboard
    myTrips: 'My Trips',
    earnings: 'Earnings',
    profile: 'Profile',
    welcomeBack: 'Welcome back',
    noTripsScheduled: 'No trips scheduled',
    noTripsMessage: "You don't have any trips assigned at the moment.",
    startTrip: 'Start Trip',
    completeTrip: 'Complete Trip',
    navigate: 'Navigate',
    totalEarnings: 'Total Earnings',
    successRate: 'Success Rate',
    professionalDriver: 'Professional Driver',
    privacy: 'Privacy',
    signOut: 'Sign Out',
    onTheWay: 'On the Way',
    cancelled: 'Cancelled',
    notes: 'Notes',
    date: 'Date',
    pickup: 'Pickup',
    vehicle: 'Vehicle'
  },
  
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    plannings: 'Plannings',
    reports: 'Rapports',
    facturations: 'Facturations',
    notesCredit: 'Notes de Crédit',
    devis: 'Devis',
    proforma: 'Proforma',
    drivers: 'Chauffeurs',
    clients: 'Clients',
    profils: 'Profils',
    compagnie: 'Compagnie',
    vehicles: 'Véhicules',
    trips: 'Trajets',
    settings: 'Paramètres',
    
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    edit: 'Modifier',
    delete: 'Supprimer',
    add: 'Ajouter',
    create: 'Créer',
    update: 'Mettre à jour',
    search: 'Rechercher',
    filter: 'Filtrer',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    
    // Dashboard
    dashboardTitle: 'Tableau de bord',
    quickAccess: 'Accès rapide',
    tripStatistics: 'Statistiques des Courses',
    totalToday: 'Total d\'Aujourd\'hui',
    tripsToDoToday: 'Course(s) à faire aujourd\'hui',
    tripsCompleted: 'Course(s) faite(s)',
    todaysTrips: 'Course(s) d\'aujourd\'hui',
    total: 'Total',
    time: 'Heure',
    driver: 'Chauffeur',
    departure: 'Départ',
    destination: 'Destination',
    passengers: 'Passager(s)',
    client: 'Client',
    payment: 'Paiement',
    noTripsToday: 'Aucune course prévue pour aujourd\'hui',
    revenue: 'Chiffre d\'affaire',
    revenueChart: 'Chiffre d\'affaire',
    refresh: 'Actualiser',
    maximize: 'Agrandir',
    chartCombinations: 'Tableau des combinaisons',
    trips: 'Courses',
    revenueAmount: 'Chiffre d\'affaire',
    unpaidInvoices: 'Factures impayées',
    averageTripPrice: 'Prix moyen d\'une course',
    months: 'Mois',
    
    // Plannings
    planningsTitle: 'Plannings',
    newTrip: 'Nouvelle course',
    addPlanning: 'Ajouter un planning',
    day: 'Jour',
    previous: 'Précédent',
    next: 'Suivant',
    noTripsFound: 'Aucun trajet trouvé',
    createTrip: 'Créer un trajet',
    tripCreatedSuccessfully: 'Cours créé avec succès !',
    failedToCreateTrip: 'Échec de la création du cours. Veuillez réessayer.',
    creatingTrip: 'Cours en cours de création...',
    driverRequired: 'Le chauffeur est requis',
    vehicleRequired: 'Le véhicule est requis',
    pickupRequired: 'Le lieu de prise en charge est requis',
    destinationRequired: 'La destination est requise',
    dateRequired: 'La date est requise',
    startTimeRequired: 'L\'heure de début est requise',
    endTimeRequired: 'L\'heure de fin est requise',
    passengersRequired: 'Le nombre de passagers est requis',
    clientRequired: 'Le nom du client est requis',
    revenueRequired: 'Les revenus sont requis',
    endTimeAfterStart: 'L\'heure de fin doit être après l\'heure de début',
    cannotExceedCapacity: 'Ne peut pas dépasser la capacité du véhicule',
    selectDriver: 'Sélectionner un chauffeur',
    selectVehicle: 'Sélectionner un véhicule',
    mail: 'Mail',
    weekOf: 'Semaine du',
    
    // Reports
    reportsTitle: 'Rapports',
    period: 'Période',
    show: 'Afficher',
    totalTrips: 'Total des trajets',
    totalRevenue: 'Revenus totaux',
    totalDistance: 'Distance totale',
    totalDuration: 'Durée totale',
    reportTitle: 'Rapport des Trajets',
    generatedOn: 'Généré le',
    all: 'Toutes',
    allDrivers: 'Tous les chauffeurs',
    allClients: 'Tous les clients',
    noReportsFound: 'Aucun rapport trouvé',
    createReport: 'Créer un rapport',
    reportCreatedSuccessfully: 'Rapport créé avec succès !',
    failedToCreateReport: 'Échec de la création du rapport. Veuillez réessayer.',
    creatingReport: 'Rapport en cours de création...',
    distance: 'Distance',
    
    // Invoicing
    invoicingTitle: 'Facturations',
    createInvoice: 'Créer une facture',
    invoiceNumber: 'Numéro de facture',
    invoiceTable: 'Table des factures',
    groupByClient: 'Grouper les factures par client',
    showMonth: 'Afficher le mois',
    display: 'Affichage',
    records: 'enregistrements',
    number: 'N°',
    dueDate: 'Date d\'échéance',
    paymentMethod: 'Méthode de paiement',
    deposit: 'Acompte',
    remark: 'Remarque',
    vatType: 'Type de TVA',
    designations: 'Désignations',
    description: 'Description',
    price: 'Prix',
    trip: 'Trajet',
    vat: 'TVA',
    totalExclVat: 'Total HTVA',
    totalInclVat: 'Total TVAC',
    clientType: 'Type de client',
    clientName: 'Nom du client',
    clientAddress: 'Adresse du client',
    postalCode: 'Code postal',
    city: 'Ville',
    clientVat: 'TVA client',
    company: 'Compagnie',
    addCompany: 'Ajouter une compagnie',
    invoiceCreatedSuccessfully: 'Facture créée avec succès !',
    failedToCreateInvoice: 'Échec de la création de la facture. Veuillez réessayer.',
    creatingInvoice: 'Création de la facture...',
    
    // Credit Notes
    creditNotesTitle: 'Notes de Crédit',
    addCreditNote: 'Ajouter une note de crédit',
    creditNoteNumber: 'Numéro de note de crédit',
    creditNotesTable: 'Table des Notes de Crédit',
    totalPrice: 'Prix total',
    print: 'Imprimer',
    creditNoteCreatedSuccessfully: 'Note de crédit créée avec succès !',
    failedToCreateCreditNote: 'Échec de la création de la note de crédit. Veuillez réessayer.',
    creatingCreditNote: 'Création de la note de crédit...',
    
    // Quotes
    quotesTitle: 'Devis',
    createQuote: 'Créer un devis',
    quoteNumber: 'Numéro de devis',
    quotesTable: 'Table des Devis',
    quoteCreatedSuccessfully: 'Devis créé avec succès !',
    failedToCreateQuote: 'Échec de la création du devis. Veuillez réessayer.',
    creatingQuote: 'Création du devis...',
    
    // Proforma
    proformaTitle: 'Proforma',
    createProforma: 'Créer une proforma',
    proformaNumber: 'Numéro de proforma',
    proformaTable: 'Table des Proformas',
    proformaCreatedSuccessfully: 'Proforma créée avec succès !',
    failedToCreateProforma: 'Échec de la création de la proforma. Veuillez réessayer.',
    creatingProforma: 'Création de la proforma...',
    
    // Drivers
    driversTitle: 'Chauffeurs',
    driversTable: 'Table des Chauffeurs',
    addDriver: 'Ajouter un chauffeur',
    modifyDriver: 'Modifier le chauffeur',
    driverStatus: 'Statut du chauffeur',
    inactive: 'Inactif',
    first: 'Premier',
    last: 'Dernier',
    driverNumber: 'Numéro de chauffeur',
    driverName: 'Nom du chauffeur',
    driverEmail: 'Email du chauffeur',
    driverPhone: 'Téléphone du chauffeur',
    driverCreatedSuccessfully: 'Chauffeur créé avec succès !',
    failedToCreateDriver: 'Échec de la création du chauffeur. Veuillez réessayer.',
    creatingDriver: 'Création du chauffeur...',
    driverUpdatedSuccessfully: 'Chauffeur mis à jour avec succès !',
    failedToUpdateDriver: 'Échec de la mise à jour du chauffeur. Veuillez réessayer.',
    updatingDriver: 'Mise à jour du chauffeur...',
    driverDeletedSuccessfully: 'Chauffeur supprimé avec succès !',
    failedToDeleteDriver: 'Échec de la suppression du chauffeur. Veuillez réessayer.',
    deletingDriver: 'Suppression du chauffeur...',
    
    // Clients
    clientsTitle: 'Clients',
    clientsTable: 'Table des Clients',
    addClient: 'Ajouter un client',
    modifyClient: 'Modifier le client',
    clientNumber: 'Numéro de client',
    companyName: 'Nom de la société',
    fullAddress: 'Adresse complète',
    address: 'Adresse',
    country: 'Pays',
    fax: 'Fax',
    email: 'Email',
    clientStatus: 'Statut du client',
    actions: 'Actions',
    clientCreatedSuccessfully: 'Client créé avec succès !',
    failedToCreateClient: 'Échec de la création du client. Veuillez réessayer.',
    creatingClient: 'Création du client...',
    clientUpdatedSuccessfully: 'Client mis à jour avec succès !',
    failedToUpdateClient: 'Échec de la mise à jour du client. Veuillez réessayer.',
    updatingClient: 'Mise à jour du client...',
    clientDeletedSuccessfully: 'Client supprimé avec succès !',
    failedToDeleteClient: 'Échec de la suppression du client. Veuillez réessayer.',
    deletingClient: 'Suppression du client...',
    
    // Profiles
    profilesTitle: 'Profils',
    profilesTable: 'Table des Profils',
    addProfile: 'Ajouter un profil',
    modifyProfile: 'Modifier le profil',
    profileName: 'Nom du profil',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    class: 'Classe',
    creationDate: 'Date de création',
    modifyAccount: 'Modifier ce compte',
    deleteAccount: 'Supprimer ce compte',
    profileClass: 'Classe du profil',
    profileCreatedSuccessfully: 'Profil créé avec succès !',
    failedToCreateProfile: 'Échec de la création du profil. Veuillez réessayer.',
    creatingProfile: 'Création du profil...',
    profileUpdatedSuccessfully: 'Profil mis à jour avec succès !',
    failedToUpdateProfile: 'Échec de la mise à jour du profil. Veuillez réessayer.',
    updatingProfile: 'Mise à jour du profil...',
    profileDeletedSuccessfully: 'Profil supprimé avec succès !',
    failedToDeleteProfile: 'Échec de la suppression du profil. Veuillez réessayer.',
    deletingProfile: 'Suppression du profil...',
    
    // Company
    companyTitle: 'Compagnie',
    companiesTitle: 'Compagnies',
    brandsTitle: 'Marques',
    addCompany: 'Ajouter une compagnie',
    modifyCompany: 'Modifier la compagnie',
    companyName: 'Nom de la compagnie',
    website: 'Site web',
    mobile: 'Mobile',
    companyCreatedSuccessfully: 'Compagnie créée avec succès !',
    failedToCreateCompany: 'Échec de la création de la compagnie. Veuillez réessayer.',
    creatingCompany: 'Création de la compagnie...',
    companyUpdatedSuccessfully: 'Compagnie mise à jour avec succès !',
    failedToUpdateCompany: 'Échec de la mise à jour de la compagnie. Veuillez réessayer.',
    updatingCompany: 'Mise à jour de la compagnie...',
    companyDeletedSuccessfully: 'Compagnie supprimée avec succès !',
    failedToDeleteCompany: 'Échec de la suppression de la compagnie. Veuillez réessayer.',
    deletingCompany: 'Suppression de la compagnie...',
    addBrand: 'Ajouter une marque',
    modifyBrand: 'Modifier la marque',
    brandName: 'Nom de la marque',
    brandStatus: 'Statut de la marque',
    brandCreatedSuccessfully: 'Marque créée avec succès !',
    failedToCreateBrand: 'Échec de la création de la marque. Veuillez réessayer.',
    creatingBrand: 'Création de la marque...',
    brandUpdatedSuccessfully: 'Marque mise à jour avec succès !',
    failedToUpdateBrand: 'Échec de la mise à jour de la marque. Veuillez réessayer.',
    updatingBrand: 'Mise à jour de la marque...',
    brandDeletedSuccessfully: 'Marque supprimée avec succès !',
    failedToDeleteBrand: 'Échec de la suppression de la marque. Veuillez réessayer.',
    deletingBrand: 'Suppression de la marque...',
    
    // Login
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    enterEmail: 'Entrez votre e-mail',
    enterPassword: 'Entrez votre mot de passe',
    signIn: 'Se connecter',
    demoCredentials: 'Identifiants de démonstration',
    driver: 'Chauffeur',
    owner: 'Propriétaire',
    professionalLimousineService: 'Gestion professionnelle de service de limousine',
    
    // Settings
    profileInformation: 'Informations du profil',
    languageRegional: 'Langue et région',
    fullName: 'Nom complet',
    changePassword: 'Changer le mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le nouveau mot de passe',
    language: 'Langue',
    timezone: 'Fuseau horaire',
    applicationInformation: 'Informations sur l\'application',
    appVersion: 'Version de l\'app',
    lastUpdated: 'Dernière mise à jour',
    build: 'Build',
    environment: 'Environnement',
    manageAccountSettings: 'Gérez vos paramètres de compte et préférences',
    nameRequired: 'Le nom est requis',
    emailRequired: 'L\'email est requis',
    emailInvalid: 'L\'email n\'est pas valide',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    passwordsNotMatch: 'Les mots de passe ne correspondent pas',
    currentPasswordRequired: 'Le mot de passe actuel est requis pour changer le mot de passe',
    settingsSaved: 'Paramètres enregistrés avec succès !',
    failedToSave: 'Échec de l\'enregistrement des paramètres. Veuillez réessayer.',
    failedToLoad: 'Échec du chargement des paramètres',
    languagePreview: 'Aperçu de la langue',
    currentLanguage: 'Langue actuelle',
    languageChangesNote: 'Les changements de langue seront appliqués après l\'enregistrement et le rafraîchissement de la page.',
    saving: 'Enregistrement...',
    saveChanges: 'Enregistrer les modifications',
    
    // Trip Form
    pickupLocation: 'Lieu de prise en charge',
    startTime: 'Heure de début',
    endTime: 'Heure de fin',
    numberOfPassengers: 'Nombre de passagers',
    clientName: 'Nom du client',
    additionalNotes: 'Notes supplémentaires',
    selectDriver: 'Sélectionner un chauffeur',
    selectVehicle: 'Sélectionner un véhicule',
    createTrip: 'Créer le trajet',
    driverRequired: 'Le chauffeur est requis',
    vehicleRequired: 'Le véhicule est requis',
    pickupRequired: 'Le lieu de prise en charge est requis',
    destinationRequired: 'La destination est requise',
    dateRequired: 'La date est requise',
    startTimeRequired: 'L\'heure de début est requise',
    endTimeRequired: 'L\'heure de fin est requise',
    passengersRequired: 'Le nombre de passagers est requis',
    clientRequired: 'Le nom du client est requis',
    revenueRequired: 'Les revenus sont requis',
    tripCreatedSuccessfully: 'Trajet créé avec succès !',
    failedToCreateTrip: 'Échec de la création du trajet. Veuillez réessayer.',
    creatingTrip: 'Création du trajet...',
    endTimeAfterStart: 'L\'heure de fin doit être après l\'heure de début',
    cannotExceedCapacity: 'Ne peut pas dépasser la capacité du véhicule',
    addVehicle: 'Ajouter un véhicule',
    manageVehicleFleet: 'Gérez votre flotte de véhicules',
    active: 'Actif',
    maintenance: 'Maintenance',
    outOfService: 'Hors service',
    currentLocation: 'Localisation actuelle',
    fuelLevel: 'Niveau de carburant',
    mileage: 'Kilométrage',
    lastService: 'Dernier service',
    nextService: 'Prochain service',
    capacity: 'Capacité',
    type: 'Type',
    overviewOfLimousineService: 'Aperçu de votre service de limousine',
    viewAll: 'Voir tout',
    quickActions: 'Actions rapides',
    manageDrivers: 'Gérer les chauffeurs',
    vehicleStatus: 'Statut des véhicules',
    hoursAgo: 'heures',
    minutesAgo: 'minutes',
    hourAgo: 'heure',
    completedStatus: 'terminé',
    activeStatus: 'actif',
    assignedStatus: 'assigné',
    manageDriverTeam: 'Gérez votre équipe de chauffeurs',
    addDriver: 'Ajouter un chauffeur',
    totalDrivers: 'Total des chauffeurs',
    offline: 'Hors ligne',
    contact: 'Contact',
    performance: 'Performance',
    location: 'Localisation',
    lastActive: 'Dernière activité',
    rating: 'Note',
    offlineStatus: 'hors ligne',
    totalVehicles: 'Total des véhicules',
    totalCapacity: 'Capacité totale',
    passengers: 'passagers',
    fuel: 'Carburant',
    mi: 'km',
    viewDetails: 'Voir les détails',
    trackLocation: 'Suivre la localisation',
    manageAllServiceTrips: 'Gérez tous vos trajets de service',
    assigned: 'Assigné',
    todaysRevenue: 'Revenus d\'aujourd\'hui',
    searchTrips: 'Rechercher des trajets...',
    allStatus: 'Tous les statuts',
    route: 'Itinéraire',
    dateTime: 'Date et heure',
    trackTrip: 'Suivre le trajet',
    noTripsFound: 'Aucun trajet trouvé',
    tryAdjustingSearch: 'Essayez d\'ajuster vos critères de recherche ou de filtrage.',
    analyticsPerformanceInsights: 'Analyses et aperçus de performance',
    export: 'Exporter',
    thisWeek: 'Cette semaine',
    thisMonth: 'Ce mois',
    lastMonth: 'Le mois dernier',
    vsYesterday: 'vs hier',
    vsLastWeek: 'vs la semaine dernière',
    vsLastMonth: 'vs le mois dernier',
    tripStatistics: 'Statistiques des trajets',
    completedTrips: 'Trajets terminés',
    activeTrips: 'Trajets actifs',
    cancelledTrips: 'Trajets annulés',
    topPerformingDrivers: 'Chauffeurs les plus performants',
    vehicleUtilizationRevenue: 'Utilisation des véhicules et revenus',
    utilization: 'Utilisation',
    excellent: 'Excellent',
    good: 'Bon',
    needsAttention: 'Nécessite une attention',
    schedule: 'Planning',
    calendar: 'Calendrier',
    today: 'Aujourd\'hui',
    tomorrow: 'Demain',
    yesterday: 'Hier',
    notifications: 'Notifications',
    notificationCenter: 'Centre de notifications',
    markAllAsRead: 'Marquer tout comme lu',
    noNotifications: 'Aucune notification',
    newTripAssigned: 'Nouveau trajet assigné',
    tripStatusChanged: 'Statut du trajet modifié',
    tripCompleted: 'Trajet terminé',
    tripCancelled: 'Trajet annulé',
    driverAssigned: 'Chauffeur assigné',
    vehicleAssigned: 'Véhicule assigné',
    paymentReceived: 'Paiement reçu',
    systemUpdate: 'Mise à jour du système',
    maintenanceReminder: 'Rappel de maintenance',
    fuelLow: 'Niveau de carburant faible',
    justNow: 'À l\'instant',
    daysAgo: 'jours',
    read: 'Lu',
    unread: 'Non lu',
    clearAll: 'Tout effacer',
    notificationSettings: 'Paramètres de notification',
    enablePushNotifications: 'Activer les notifications push',
    enableEmailNotifications: 'Activer les notifications email',
    enableSMSNotifications: 'Activer les notifications SMS',
    tripNotifications: 'Notifications de trajet',
    systemNotifications: 'Notifications système',
    maintenanceNotifications: 'Notifications de maintenance',
    notificationSound: 'Son de notification',
    vibrationEnabled: 'Vibration activée',
    
    // Driver Dashboard
    myTrips: 'Mes trajets',
    earnings: 'Gains',
    profile: 'Profil',
    welcomeBack: 'Bon retour',
    noTripsScheduled: 'Aucun trajet programmé',
    noTripsMessage: "Vous n'avez aucun trajet assigné pour le moment.",
    startTrip: 'Commencer le trajet',
    completeTrip: 'Terminer le trajet',
    navigate: 'Naviguer',
    totalEarnings: 'Gains totaux',
    successRate: 'Taux de réussite',
    professionalDriver: 'Chauffeur professionnel',
    privacy: 'Confidentialité',
    signOut: 'Se déconnecter',
    onTheWay: 'En route',
    cancelled: 'Annulé',
    notes: 'Notes',
    date: 'Date',
    pickup: 'Prise en charge',
    vehicle: 'Véhicule'
  },
  
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    plannings: 'المواعيد',
    reports: 'التقارير',
    facturations: 'الفواتير',
    notesCredit: 'إشعارات الائتمان',
    devis: 'عروض الأسعار',
    proforma: 'الفاتورة الأولية',
    drivers: 'السائقين',
    clients: 'العملاء',
    profils: 'الملفات الشخصية',
    compagnie: 'الشركة',
    vehicles: 'المركبات',
    trips: 'الرحلات',
    settings: 'الإعدادات',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    create: 'إنشاء',
    update: 'تحديث',
    search: 'بحث',
    filter: 'تصفية',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    
    // Login
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    enterEmail: 'أدخل بريدك الإلكتروني',
    enterPassword: 'أدخل كلمة المرور',
    signIn: 'تسجيل الدخول',
    demoCredentials: 'بيانات الاعتماد التجريبية',
    driver: 'السائق',
    owner: 'المالك',
    professionalLimousineService: 'إدارة خدمة الليموزين المهنية',
    
    // Settings
    profileInformation: 'معلومات الملف الشخصي',
    languageRegional: 'اللغة والمنطقة',
    fullName: 'الاسم الكامل',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    language: 'اللغة',
    timezone: 'المنطقة الزمنية',
    applicationInformation: 'معلومات التطبيق',
    appVersion: 'إصدار التطبيق',
    lastUpdated: 'آخر تحديث',
    build: 'البناء',
    environment: 'البيئة',
    manageAccountSettings: 'إدارة إعدادات حسابك وتفضيلاتك',
    nameRequired: 'الاسم مطلوب',
    emailRequired: 'البريد الإلكتروني مطلوب',
    emailInvalid: 'البريد الإلكتروني غير صحيح',
    passwordMinLength: 'كلمة المرور يجب أن تحتوي على 6 أحرف على الأقل',
    passwordsNotMatch: 'كلمات المرور غير متطابقة',
    currentPasswordRequired: 'كلمة المرور الحالية مطلوبة لتغيير كلمة المرور',
    settingsSaved: 'تم حفظ الإعدادات بنجاح!',
    failedToSave: 'فشل في حفظ الإعدادات. يرجى المحاولة مرة أخرى.',
    failedToLoad: 'فشل في تحميل الإعدادات',
    languagePreview: 'معاينة اللغة',
    currentLanguage: 'اللغة الحالية',
    languageChangesNote: 'سيتم تطبيق تغييرات اللغة بعد الحفظ وتحديث الصفحة.',
    saving: 'جاري الحفظ...',
    saveChanges: 'حفظ التغييرات',
    
    // Trip Form
    pickupLocation: 'موقع الاستلام',
    startTime: 'وقت البداية',
    endTime: 'وقت النهاية',
    numberOfPassengers: 'عدد الركاب',
    clientName: 'اسم العميل',
    additionalNotes: 'ملاحظات إضافية',
    selectDriver: 'اختر سائق',
    selectVehicle: 'اختر مركبة',
    createTrip: 'إنشاء الرحلة',
    driverRequired: 'السائق مطلوب',
    vehicleRequired: 'المركبة مطلوبة',
    pickupRequired: 'موقع الاستلام مطلوب',
    destinationRequired: 'الوجهة مطلوبة',
    dateRequired: 'التاريخ مطلوب',
    startTimeRequired: 'وقت البداية مطلوب',
    endTimeRequired: 'وقت النهاية مطلوب',
    passengersRequired: 'عدد الركاب مطلوب',
    clientRequired: 'اسم العميل مطلوب',
    revenueRequired: 'الإيرادات مطلوبة',
    tripCreatedSuccessfully: 'تم إنشاء الرحلة بنجاح!',
    failedToCreateTrip: 'فشل في إنشاء الرحلة. يرجى المحاولة مرة أخرى.',
    creatingTrip: 'جاري إنشاء الرحلة...',
    endTimeAfterStart: 'وقت النهاية يجب أن يكون بعد وقت البداية',
    cannotExceedCapacity: 'لا يمكن تجاوز سعة المركبة',
    addVehicle: 'إضافة مركبة',
    manageVehicleFleet: 'إدارة أسطول المركبات',
    active: 'نشط',
    maintenance: 'صيانة',
    outOfService: 'خارج الخدمة',
    currentLocation: 'الموقع الحالي',
    fuelLevel: 'مستوى الوقود',
    mileage: 'المسافة المقطوعة',
    lastService: 'آخر خدمة',
    nextService: 'الخدمة التالية',
    capacity: 'السعة',
    type: 'النوع',
    overviewOfLimousineService: 'نظرة عامة على خدمة الليموزين',
    viewAll: 'عرض الكل',
    quickActions: 'إجراءات سريعة',
    manageDrivers: 'إدارة السائقين',
    vehicleStatus: 'حالة المركبات',
    hoursAgo: 'ساعات',
    minutesAgo: 'دقائق',
    hourAgo: 'ساعة',
    completedStatus: 'مكتمل',
    activeStatus: 'نشط',
    assignedStatus: 'مخصص',
    manageDriverTeam: 'إدارة فريق السائقين',
    addDriver: 'إضافة سائق',
    totalDrivers: 'إجمالي السائقين',
    offline: 'غير متصل',
    contact: 'التواصل',
    performance: 'الأداء',
    location: 'الموقع',
    lastActive: 'آخر نشاط',
    rating: 'التقييم',
    offlineStatus: 'غير متصل',
    totalVehicles: 'إجمالي المركبات',
    totalCapacity: 'السعة الإجمالية',
    passengers: 'ركاب',
    fuel: 'الوقود',
    mi: 'كم',
    viewDetails: 'عرض التفاصيل',
    trackLocation: 'تتبع الموقع',
    manageAllServiceTrips: 'إدارة جميع رحلات الخدمة',
    assigned: 'مخصص',
    todaysRevenue: 'إيرادات اليوم',
    searchTrips: 'البحث في الرحلات...',
    allStatus: 'جميع الحالات',
    route: 'المسار',
    dateTime: 'التاريخ والوقت',
    trackTrip: 'تتبع الرحلة',
    noTripsFound: 'لم يتم العثور على رحلات',
    tryAdjustingSearch: 'حاول تعديل معايير البحث أو التصفية.',
    analyticsPerformanceInsights: 'التحليلات ورؤى الأداء',
    export: 'تصدير',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    vsYesterday: 'مقارنة بالأمس',
    vsLastWeek: 'مقارنة بالأسبوع الماضي',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    tripStatistics: 'إحصائيات الرحلات',
    completedTrips: 'الرحلات المكتملة',
    activeTrips: 'الرحلات النشطة',
    cancelledTrips: 'الرحلات الملغية',
    topPerformingDrivers: 'أفضل السائقين أداءً',
    vehicleUtilizationRevenue: 'استخدام المركبات والإيرادات',
    utilization: 'الاستخدام',
    excellent: 'ممتاز',
    good: 'جيد',
    needsAttention: 'يحتاج إلى انتباه',
    schedule: 'الجدولة',
    calendar: 'التقويم',
    today: 'اليوم',
    tomorrow: 'غداً',
    yesterday: 'أمس',
    week: 'الأسبوع',
    month: 'الشهر',
    noTripsToday: 'لا توجد رحلات مجدولة لليوم',
    upcomingTrips: 'الرحلات القادمة',
    tripDetails: 'تفاصيل الرحلة',
    startLocation: 'موقع البداية',
    endLocation: 'موقع النهاية',
    duration: 'المدة',
    estimatedArrival: 'الوصول المتوقع',
    clientContact: 'جهة اتصال العميل',
    specialInstructions: 'تعليمات خاصة',
    viewOnMap: 'عرض على الخريطة',
    markAsCompleted: 'وضع علامة كمكتمل',
    markAsStarted: 'وضع علامة كمبدأ',
    cancelTrip: 'إلغاء الرحلة',
    rescheduleTrip: 'إعادة جدولة الرحلة',
    addToCalendar: 'إضافة إلى التقويم',
    calendarView: 'عرض التقويم',
    listView: 'عرض القائمة',
    previousWeek: 'الأسبوع السابق',
    nextWeek: 'الأسبوع التالي',
    previousMonth: 'الشهر السابق',
    nextMonth: 'الشهر التالي',
    notifications: 'الإشعارات',
    notificationCenter: 'مركز الإشعارات',
    markAllAsRead: 'وضع علامة مقروء على الكل',
    noNotifications: 'لا توجد إشعارات',
    newTripAssigned: 'تم تعيين رحلة جديدة',
    tripStatusChanged: 'تم تغيير حالة الرحلة',
    tripCompleted: 'تم إكمال الرحلة',
    tripCancelled: 'تم إلغاء الرحلة',
    driverAssigned: 'تم تعيين السائق',
    vehicleAssigned: 'تم تعيين المركبة',
    paymentReceived: 'تم استلام الدفع',
    systemUpdate: 'تحديث النظام',
    maintenanceReminder: 'تذكير الصيانة',
    fuelLow: 'مستوى الوقود منخفض',
    justNow: 'الآن',
    daysAgo: 'أيام',
    read: 'مقروء',
    unread: 'غير مقروء',
    clearAll: 'مسح الكل',
    notificationSettings: 'إعدادات الإشعارات',
    enablePushNotifications: 'تفعيل الإشعارات الفورية',
    enableEmailNotifications: 'تفعيل إشعارات البريد الإلكتروني',
    enableSMSNotifications: 'تفعيل إشعارات الرسائل النصية',
    tripNotifications: 'إشعارات الرحلات',
    systemNotifications: 'إشعارات النظام',
    maintenanceNotifications: 'إشعارات الصيانة',
    notificationSound: 'صوت الإشعار',
    vibrationEnabled: 'تفعيل الاهتزاز',
    
    // Driver Dashboard
    myTrips: 'رحلاتي',
    earnings: 'الأرباح',
    profile: 'الملف الشخصي',
    welcomeBack: 'مرحباً بعودتك',
    noTripsScheduled: 'لا توجد رحلات مجدولة',
    noTripsMessage: 'ليس لديك أي رحلات مخصصة في الوقت الحالي.',
    startTrip: 'بدء الرحلة',
    completeTrip: 'إكمال الرحلة',
    navigate: 'التنقل',
    totalEarnings: 'إجمالي الأرباح',
    successRate: 'معدل النجاح',
    professionalDriver: 'سائق محترف',
    privacy: 'الخصوصية',
    signOut: 'تسجيل الخروج',
    onTheWay: 'في الطريق',
    cancelled: 'ملغي',
    notes: 'الملاحظات',
    date: 'التاريخ',
    pickup: 'الاستلام',
    vehicle: 'المركبة'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    // Load language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('limostar-language') || 'en'
    setLanguage(savedLanguage)
    setIsLoading(false)
  }, [])

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('limostar-language', newLanguage)
  }

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key
  }

  const value = {
    language,
    changeLanguage,
    t,
    isLoading
  }

  if (isLoading) {
    return <div>Loading...</div>
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}
